package str;
import allOther.*;

public class Main {
    public static void main(String[] args){
        Time time = new Time(WhatTime.MORNING);
        System.out.println(time.describe());
        Newspaper newspaper = new Newspaper("Новости");
        Corporation corporation = new Corporation("учреждение Акционерного общества гигантских растений");
        corporation.appear();
        newspaper.announcement(corporation.describe());
        System.out.println(newspaper.describe());
        City city = new City("Давилон");
        System.out.println(city.whereWeAre());
        Bank bank = new Bank("Банк");
        Robber robber = new Robber("Грабители");
        Rob rob = new Rob(true);
        System.out.println(rob.getResult());
        robber.camouflage(false);
        robber.bankLoot(bank, time, rob);
        System.out.println(bank.describe());
        city.announcement("ограбление");
        System.out.println(city.describe());
        Bandit bandit = new Bandit("Бандиты", 40);
        Bandit headBandit = new Bandit("Главный Бандит", 1);
        Car car = new Car();
        car.here();
        bandit.know();
        bandit.come(car);
        bandit.condition(ConditionSet.ALIVE, "никуда");
        headBandit.condition(ConditionSet.DAMAGED, "ухо");
        Police police = new Police("Полицейские");
        System.out.println(bandit.describe());
        FireGun pistol = new FireGun("Пистолет", 10);
        FireGun kar98k = new FireGun("Винтовка", 5);
        FireGun autogun = new FireGun("Автомат", 30);
        Granade granade = new Granade("Граната", 7);
        bandit.addWeapon(pistol);
        bandit.addWeapon(kar98k);
        bandit.addWeapon(autogun);
        bandit.addWeapon(granade);
        System.out.println(bandit.useWeaponFireGun(pistol, police));
        System.out.println(bandit.useWeaponFireGun(kar98k, police));
        System.out.println(bandit.useWeaponFireGun(autogun, police));
        System.out.println(bandit.useWeaponGranade(granade, police));
        System.out.println(police.describe());
        BankWorker bankWorker = new BankWorker("Все Работники банка");
        BankWorker cashier = new BankWorker("Кассир");
        Box box = new Box("Сундук", "несгораемый");
        cashier.isBoxThere(box);
        System.out.println(bandit.useWeaponFireGun(pistol, bankWorker));
        System.out.println(bandit.useWeaponFireGun(autogun, bankWorker));
        System.out.println(bandit.useWeaponFireGun(pistol, cashier));
        System.out.println(bandit.useWeaponFireGun(autogun, cashier));
        System.out.println(bankWorker.describe());
        System.out.println(cashier.describe());
        bandit.getCondition();
        headBandit.getCondition();
        Alone neznayka = new Alone("Незнайка");
        Alone miga = new Alone("Мига");
        Alone kozlik = new Alone("Козлик");
        Alone julio = new Alone("Джулио");
        StockExchange binance = new StockExchange();
        neznayka.come();
        miga.come();
        kozlik.come();
        System.out.println(neznayka.describe());
        System.out.println(miga.describe());
        System.out.println(kozlik.describe());
        System.out.println(binance.buy(3, neznayka));
        Buyer buyer = new Buyer("Покупатели акций");
        System.out.println(buyer.describe());
        ShowInfo showInfo = (a, b) -> "Информация о бирже: кол-во акций: " + String.valueOf(a) + ", кол-во денег: " + String.valueOf(b);
        Integer a = binance.getAmount();
        Integer b = binance.getMoney();
        System.out.println(showInfo.inf(a, b));
        julio.come();
        julio.know();
        System.out.println(julio.describe());
        julio.tell("о ограблении ", neznayka);
        julio.tell("о ограблении ", miga);
        julio.tell("о ограблении ", kozlik);
    }
}